### ISSUE TITLE
How We can start this app?

### ISSUE THREAD

**Issue by keyldev** [THRUWOL/JavaRestApp_kafka-producer#1]
Please, add readme for us

**Comment by THRUWOL** [comment]
This is in the development phase and READ.me with the launch doesn't make sense to add yet, as many of the project's dependencies may change.

**Comment by THRUWOL** [comment]
> Please, add readme for us

This is in the development phase and READ.me with the launch doesn't make sense to add yet, as many of the project's dependencies may change.
